sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - bower install
script:
  - ./node_modules/.bin/karma start --single-run --browsers PhantomJS karma.conf.js
services: mongodb
